project_id = "egbaykisnkwuepippnab"

[functions.generate-recommendations]
verify_jwt = false

[functions.generate-business-plan]
verify_jwt = false

[functions.get-suppliers]
verify_jwt = false

[functions.suggest-ideas]
verify_jwt = false
